'use strict'

const SERVER_IP = 'http://cfd-webapi.chinacloudapp.cn'

export const GET_PHONE_CODE_API = SERVER_IP + '/api/sendCode'
export const PHONE_NUM_LOGIN_API = SERVER_IP + '/api/user/signupByPhone'
export const WECHAT_LOGIN_API = SERVER_IP + '/api/user/signupByWeChat'
export const GET_USER_INFO_API = SERVER_IP + '/api/user/me'
export const SET_USER_NICKNAME_API = SERVER_IP + '/api/user/nickname'
export const GET_USER_BOOKMARK_LIST_API = SERVER_IP + '/api/security/bookmark'
export const GET_US_STOCK_TOP_GAIN_API = SERVER_IP + '/api/security/stock/topGainer'
export const GET_US_STOCK_TOP_LOSER_API = SERVER_IP + '/api/security/stock/topLoser'
export const GET_INDEX_LIST_API = SERVER_IP + '/api/security/index'
export const GET_FX_LIST_API = SERVER_IP + '/api/security/fx'
export const GET_FUTURE_LIST_API = SERVER_IP + '/api/security/futures'
export const GET_SEARCH_STOCK_API = SERVER_IP + '/api/security/search'
export const GET_STOCK_DETAIL_API = SERVER_IP + '/api/security/<stockCode>'
export const GET_STOCK_PRICE_TODAY_API = SERVER_IP + '/api/quote/<stockCode>/tick/<chartType>'
export const GET_OPEN_POSITION_API = SERVER_IP + '/api/position/open'
export const GET_HOMEPAGE_BANNER_API = SERVER_IP + '/api/banner'
export const OWN_STOCK_LIST_API = SERVER_IP + '/api/security/bookmark'
export const POST_CREATE_POSITION_API = SERVER_IP + '/api/position'
export const POST_DELETE_POSITION_API = SERVER_IP + '/api/position/net'

export const PARAMETER_PHONE = 'phone'
export const PARAMETER_VERFICATION_CODE = 'verifyCode'
export const PARAMETER_NICKNAME = 'nickname'
export const PARAMETER_STOCKIDS = 'securityIds'

export const PARAMETER_CHARTTYPE_TODAY = 'today'
export const PARAMETER_CHARTTYPE_WEEK = 'week'
export const PARAMETER_CHARTTYPE_MONTH = 'month'
