//
//  AppDelegate.swift
//  CFD
//
//  Created by william on 16/3/3.
//  Copyright © 2016年 tradehero. All rights reserved.
//

import UIKit

struct Platform {
	static let isSimulator: Bool = {
		var isSim = false
		#if arch(i386) || arch(x86_64)
			isSim = true
		#endif
		return isSim
	}()
}

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
	
	var rnRootViewController: UIViewController!
	var window: UIWindow?
	var nativeData: NativeData?
	
	func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
		// Override point for customization after application launch.
		TalkingData.sessionStarted("9E5885AAFCB333653031970C2AF5614E", withChannelId: "AppStore")
		TalkingDataAppCpa.init("605dc6928f4c4244a889282a7ee132cf", withChannelId: "AppStore")
		
		// register push notification
		application.registerUserNotificationSettings(UIUserNotificationSettings(forTypes: [.Alert, .Badge, .Sound] , categories: nil))
		application.registerForRemoteNotifications()
		
		if (!TalkingData.handlePushMessage(launchOptions)) {
			// 非来自TalkingData的消息，可以在此处处理该消息。
		}
		
		// meiqia
		MQManager.initWithAppkey("2a59beff6f1875815ea399fdad79a46e", completion:{ (clientId, error) in
			if((error) != nil) {
				print("init meiqia error:", error)
			}
			else {
				print("init meiqia completion:", clientId)
			}
		})
		
		// initialize the rootView to fetch JS from the dev server
		/**
		* Loading JavaScript code - uncomment the one you want.
		*
		* OPTION 1
		* Load from development server. Start the server from the repository root:
		*
		* $ npm start
		*
		* To run on device, change `localhost` to the IP address of your computer
		* (you can get this by typing `ifconfig` into the terminal and selecting the
		* `inet` value under `en0:`) and make sure your computer and iOS device are
		* on the same Wi-Fi network.
		*/
		let jsCodeLocation:NSURL?
		if Platform.isSimulator {
			jsCodeLocation = NSURL(string: "http://localhost:8081/index.ios.bundle?platform=ios&dev=true")
		} else {
		/**
		* OPTION 2
		* Load from pre-bundled file on disk. The static bundle is automatically
		* generated by "Bundle React Native code and images" build step.
		*/
            jsCodeLocation = RCTHotUpdate.bundleURL();
//			jsCodeLocation = NSBundle.mainBundle().URLForResource("main", withExtension: "jsbundle")
//			jsCodeLocation = NSURL(string: "http://192.168.20.140:8081/index.ios.bundle?platform=ios&dev=true")
		}
		
		let rootView = RCTRootView(bundleURL:jsCodeLocation,moduleName: "TH_CFD",initialProperties:nil,launchOptions:launchOptions)
		
		// Initialize a Controller to use view as React View
		let rootViewController:UIViewController = UIViewController()
		rootViewController.view = rootView
		let loadingView = UIImageView(frame: UIScreen.mainScreen().bounds)
		loadingView.image = UIImage(named: "frontPage.jpg")
		rootView.loadingView = loadingView
		self.rnRootViewController = rootViewController
		
		// Set window to use rootViewController
		self.window = UIWindow(frame: UIScreen.mainScreen().bounds)
		self.window?.rootViewController = rootViewController
		self.window?.makeKeyAndVisible()
		
		let home = NSHomeDirectory()
		print(home)
		return true
	}
	
	func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
		return RCTLinkingManager.application(application, openURL: url, sourceApplication: sourceApplication, annotation: annotation)
	}
	
	func applicationWillResignActive(application: UIApplication) {
		// Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
		// Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
	}
	
	func applicationDidEnterBackground(application: UIApplication) {
		// Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
		// If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
		MQManager.closeMeiqiaService()
	}
	
	func applicationWillEnterForeground(application: UIApplication) {
		// Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
		MQManager.openMeiqiaService()
	}
	
	func applicationDidBecomeActive(application: UIApplication) {
		// Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
	}
	
	func applicationWillTerminate(application: UIApplication) {
		// Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
	}

//	// Only if your app is using [Universal Links](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html).
//	func application(application: UIApplication, continueUserActivity userActivity: NSUserActivity, restorationHandler: ([AnyObject]?) -> Void) -> Bool {
//		return RCTLinkingManager.application(application, continueUserActivity: userActivity, restorationHandler: restorationHandler)
//	}

	func application(application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: NSData) {
		print("Device token:", deviceToken)
		TalkingData.setDeviceToken(deviceToken)
		MQManager.registerDeviceToken(deviceToken)
	}
	
	func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject]) {
		if (!TalkingData.handlePushMessage(userInfo)) {
			// 非来自TalkingData的消息，可以在此处处理该消息。
		}
	}
	
	func application(application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: NSError) {
		print("Register remote notification failed")
		print("no device token")
	}

}

